title: Juergen Unseld
description:

url: https://jporzelt.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Aktuelles
   url: /index.html
 - title: Galerie
   url: /galerie
 - title: Lebenslauf
   url: /lebenslauf

social:
   github: jporzelt
   twitter:
   facebook:
   email: jporzelt@gmail.bla

google_analytics:
